version: '3.8'
services:
  dev-db:
    container_name: 'postgresql-container'
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=POSTGRES_DB
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest
